---
detectors:
  IrresponsibleModule:
    enabled: false

  UtilityFunction:
    public_methods_only: true

directories:
  'app/controllers':
    InstanceVariableAssumption:
      enabled: false
  'app/mailers':
    InstanceVariableAssumption:
      enabled: false

exclude_paths:
  - 'db/migrate'
